http:
  port: 9084
  adminPort: 9085

  # The minimum number of threads to keep running to process incoming HTTP requests.
  minThreads: 256

  # The maximum number of threads to keep running to process incoming HTTP requests.
  maxThreads: 1024

  # If true, the HTTP server will prefer X-Forwarded headers over their non-forwarded equivalents.
  useForwardedHeaders: true

  # If non-zero, the server will allow worker threads to finish
  # processing requests after the server socket has been closed for
  # the given amount of time.
  shutdownGracePeriod: 5s

  # HTTP request log settings.
  requestLog:

    # Settings for logging to stdout.
    console:

      # If true, log requests to stdout.
      enabled: false

      # The time zone in which dates should be displayed.
      timeZone: UTC

      # A custom Logback format string.
      logFormat: null

    # Settings for logging to a file.
    file:

      # If true, log requests to a file.
      enabled: true

      # The time zone in which dates should be displayed.
      timeZone: UTC

      # A custom Logback format string.
      logFormat: null

      # The file to which statements will be logged.
      # If enabled is true, this must be specified.
      currentLogFilename: ./logs/requests.log

      # If true, log files are rotated and archived.
      archive: true

      # When the log file rolls over, the file will be archived to
      # example-2012-03-15.log.gz, example.log will be truncated,
      # and new requests written to it.
      # If archive is true, this must be specified.
      archivedLogFilenamePattern: ./logs/requests-%d.log.gz

      # The maximum number of log files to archive.
      archivedFileCount: 30

dbConfiguration:
  host: localhost
  port: 27017
  database: test

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO,
  # DEBUG, TRACE, or ALL.
  level: INFO

  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: ALL

    # The time zone in which dates should be displayed.
    timeZone: UTC

    # A custom Logback format string.
    logFormat: "%-5p [%d{ISO8601,UTC}] %mdc{Tracking-Id} %mdc{Request-Uri} %mdc{Ip-Address} %c: %m%n%ex"

  # Settings for logging to a file.
  file:

    # If true, write log statements to a file.
    enabled: true

    # Do not write log statements below this threshold to the file.
    threshold: ALL

    # The time zone in which dates should be displayed.
    timeZone: UTC

    # A custom Logback format string.
    logFormat: "%-5p [%d{ISO8601,UTC}] %mdc{Tracking-Id} %mdc{Request-Uri} %mdc{Ip-Address} %c: %m%n%ex"

    # The file to which statements will be logged.
    #
    # If enabled is true, this must be specified.
    currentLogFilename: ./logs/service.log

    # If true, log files are rotated and archived.
    archive: true

    # When the log file rolls over, the file will be archived to
    # app-2012-03-15.log.gz, example.log will be truncated,
    # and new statements written to it.
    #
    # If archive is true, this must be specified.
    archivedLogFilenamePattern: ./logs/service-%d.log.gz

    # The maximum number of log files to archive.
    archivedFileCount: 30
